name: Build HypeType

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download AutoHotkey Portable
        shell: pwsh
        run: |
          Write-Host "Downloading AutoHotkey v1.1 Portable..."
          Invoke-WebRequest -Uri "https://github.com/AutoHotkey/AutoHotkey/releases/download/v1.1.37.02/AutoHotkey_1.1.37.02.zip" -OutFile "AutoHotkey.zip"
          Expand-Archive -Path "AutoHotkey.zip" -DestinationPath "AutoHotkey"
          Write-Host "AutoHotkey Portable extracted successfully"

      - name: Compile AHK to EXE
        shell: pwsh
        run: |
          Write-Host "Starting compilation..."
          & ".\AutoHotkey\Compiler\Ahk2Exe.exe" /in "scr\main.ahk" /out "./hypetype.exe" /icon "assets\icon.ico" /base ".\AutoHotkey\AutoHotkeyU32.exe"
          Write-Host "Checking output file location:"
          Get-ChildItem -Path . -Filter hypetype.exe -Recurse

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hypetype
          path: src/hypetype.exe