name: Build hypehype

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download AutoHotkey Portable
        shell: pwsh
        run: |
          Write-Host "Downloading AutoHotkey v2.0 Portable..."
          Invoke-WebRequest -Uri "https://github.com/AutoHotkey/AutoHotkey/releases/download/v2.0.18/AutoHotkey_2.0.18.zip" -OutFile "AutoHotkey.zip"
          Expand-Archive -Path "AutoHotkey.zip" -DestinationPath "AutoHotkey"
          Get-ChildItem -Path "AutoHotkey" -Recurse
          Write-Host "AutoHotkey Portable extracted successfully"

      - name: Compile AHK to EXE
        shell: pwsh
        run: |
          Write-Host "Starting compilation..."
          & ".\AutoHotkey\v2\Compiler\Ahk2Exe.exe" /in "main.ahk" /out "hypetype.exe" /icon "assets\icon.ico" /base ".\AutoHotkey\v2\AutoHotkey64.exe"
          Write-Host "Compilation completed"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hypetype
          path: hypetype.exe