name: Build HypeType

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download AutoHotkey Portable
        shell: pwsh
        run: |
          Write-Host "Downloading AutoHotkey v1.1 Portable..."
          Invoke-WebRequest -Uri "https://github.com/AutoHotkey/AutoHotkey/releases/download/v1.1.37.02/AutoHotkey_1.1.37.02.zip" -OutFile "AutoHotkey.zip"
          Expand-Archive -Path "AutoHotkey.zip" -DestinationPath "AutoHotkey"
          Write-Host "AutoHotkey Portable extracted successfully"

      - name: Compile AHK to EXE
        shell: pwsh
        run: |
          Write-Host "Starting compilation..."
          $sourcePath = Join-Path -Path $pwd -ChildPath "scr\main.ahk"
          $outputPath = Join-Path -Path $pwd -ChildPath "scr\hypetype.exe"
          & ".\AutoHotkey\Compiler\Ahk2Exe.exe" /in "$sourcePath" /out "$outputPath" /icon "assets\icon.ico" /base ".\AutoHotkey\AutoHotkeyU32.exe"
          Write-Host "Output path is: $outputPath"
          if (Test-Path $outputPath) {
              Write-Host "File created successfully!"
          }

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ./scr/hypetype.exe