name: Build HypeType

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download AutoHotkey Portable
        run: |
          Write-Host "Downloading AutoHotkey v1.1 Portable..."
          Invoke-WebRequest -Uri "https://www.autohotkey.com/download/1.1/AutoHotkey_1.1.34.03.zip" -OutFile "AutoHotkey.zip"
          Expand-Archive -Path "AutoHotkey.zip" -DestinationPath "AutoHotkey"
          Write-Host "AutoHotkey Portable extracted successfully"

      - name: Compile AHK to EXE
        run: |
          Write-Host "Starting compilation..."
          & "AutoHotkey\Compiler\Ahk2Exe.exe" /in "main.ahk" /out "hypetype.exe" /icon "assets\icon.ico" /base "AutoHotkey\AutoHotkeyU32.exe"
          Write-Host "Compilation completed"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: hypetype
          path: hypetype.exe